### ISSUE TITLE
token revoke

### ISSUE THREAD

**Issue by ray007** [bpedroza/js-pkce#14]
It would be nice to also support revoking of token so a user can be logged out.
See https://datatracker.ietf.org/doc/html/rfc7009

**Comment by bpedroza** [comment]
I will look into this. Thanks for opening the issue.

**Comment by bpedroza** [comment]
This functionality is actually not well defined for the PKCE flow. The RFC specifically states that basic authorization is required when the client is confidential, but it does not explicitly state expectations when the client is not confidential.

I have seen some server implementations where the Authorization header is still expected with a blank password, and others where the client_id is expected in the request body.

The latter seems to be the more frequently used convention, so that's what I'm going with.
